services:
  web:
    build: .
    container_name: aggieseek
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - app-network
    depends_on:
      - nginx
  
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge